import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";

/**
 * Discord/Slack developer communities. Most BAN unsolicited promo (HIGH); those
 * with a dedicated #showcase/#show-and-tell channel are MEDIUM (noted in rules).
 */
export const communities: Seed[] = [
  {
    slug: "discord-reactiflux",
    name: "Reactiflux",
    platform: Platform.DISCORD,
    url: "https://discord.gg/reactiflux",
    audienceDesc: "~200k React & JavaScript developers",
    rules: "No commercial solicitation, marketing, or lead-gen outside dedicated channels. Paid recruiting only in #job-board and non-commercial projects in #looking-for-group; episodic content (videos, podcasts) may be shared at most every 2 weeks. No general #showcase for products.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday afternoons (US/EU overlap)",
    tags: ["developers", "frontend", "webdev", "javascript", "react", "community"],
  },
  {
    slug: "discord-vue-land",
    name: "Vue Land",
    platform: Platform.DISCORD,
    url: "https://discord.gg/vue",
    audienceDesc: "~40k Vue.js developers",
    rules: "Official Vue.js community server focused on help and discussion. Self-promotion is restricted to the dedicated #show-and-tell channel; posting product links elsewhere is treated as spam. Read #rules before sharing.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in #show-and-tell",
    tags: ["developers", "frontend", "webdev", "javascript", "vue", "community"],
  },
  {
    slug: "discord-programmers-hangout",
    name: "The Programmer's Hangout",
    platform: Platform.DISCORD,
    url: "https://discord.gg/programming",
    audienceDesc: "~100k general programmers",
    rules: "Strict no-advertising policy: do not promote anything you stand to benefit from (servers, sites, YouTube, blogs). Exceptions are rare and must be requested via ModMail first. Unsolicited self-promo is removed and can lead to a ban.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday evenings",
    tags: ["developers", "technical", "fullstack", "opensource", "community"],
  },
  {
    slug: "discord-devcord",
    name: "devcord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/devcord",
    audienceDesc: "~45k web developers & learners",
    rules: "Web-dev community for help, feedback, and remote-job sharing. Self-promotion belongs in the dedicated showcase/self-promo channel only; dropping product links in help or general chat is not allowed. Check the rules channel on join.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in the self-promo channel",
    tags: ["developers", "webdev", "frontend", "fullstack", "javascript", "community"],
  },
  {
    slug: "discord-rust-community",
    name: "Rust Programming Language Community",
    platform: Platform.DISCORD,
    url: "https://discord.gg/rust-lang-community",
    audienceDesc: "~70k Rust developers",
    rules: "Large community-run Rust server (the official one is now a read-only archive). Enforces the Rust Code of Conduct; share projects in the dedicated showcase/#projects channel rather than general help channels. Unsolicited ads elsewhere are removed.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in #showcase",
    tags: ["developers", "backend", "technical", "opensource", "rust", "community"],
  },
  {
    slug: "discord-python",
    name: "Python Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/python",
    audienceDesc: "~350k Python developers",
    rules: "Do not post unapproved advertising and do not offer or ask for paid work. Projects may be shown in off-topic channels but there is no promotion-friendly showcase; the mods explicitly suggest Reddit for showing off products. Unsolicited promo is removed.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday afternoons",
    tags: ["developers", "backend", "technical", "opensource", "python", "community"],
  },
  {
    slug: "discord-nextjs",
    name: "Next.js Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/nextjs",
    audienceDesc: "~110k Next.js developers",
    rules: "Vercel's official Next.js server for support and discussion. Share what you build in the dedicated #showcase channel; posting product or marketing links in help/general channels is treated as spam. Read the rules on join.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in #showcase",
    tags: ["developers", "frontend", "webdev", "javascript", "nextjs", "react", "community"],
  },
  {
    slug: "discord-tailwind-css",
    name: "Tailwind CSS Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/tailwindcss",
    audienceDesc: "~40k Tailwind CSS & frontend developers",
    rules: "Community server for questions, feedback, and sharing what you've built with Tailwind. Use the dedicated show-and-tell/#built-with-tailwind channel for projects; keep general and help channels free of promo links.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in the show-and-tell channel",
    tags: ["developers", "frontend", "webdev", "design", "css", "community"],
  },
  {
    slug: "discord-astro",
    name: "Astro Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/astrodotbuild",
    audienceDesc: "~36k Astro developers",
    rules: "Official Astro community server for support and discussion. Projects belong in the dedicated #showcase channel (and sites can be submitted to the website's Showcase); avoid dropping product links in support threads or general chat.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in #showcase",
    tags: ["developers", "frontend", "webdev", "javascript", "typescript", "community"],
  },
  {
    slug: "discord-supabase",
    name: "Supabase Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/supabase",
    audienceDesc: "~50k developers building on Supabase",
    rules: "Official Supabase community with dedicated channels including a #showcase where members share what they've built. Keep self-promotion to #showcase; support and general channels are for help, not marketing. Read #rules first.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in #showcase",
    tags: ["developers", "backend", "api", "saas", "opensource", "community"],
  },
  {
    slug: "slack-gophers",
    name: "Gophers Slack",
    platform: Platform.SLACK,
    url: "https://invite.slack.golangbridge.org/",
    audienceDesc: "~40k Go developers",
    rules: "Community Slack run by GolangBridge (invite via the form). Self-promotion is limited to the dedicated #showandtell channel; posting product links in help or general channels is discouraged and can get you removed.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in #showandtell",
    tags: ["developers", "backend", "technical", "opensource", "golang", "community"],
  },
  {
    slug: "slack-rands-leadership",
    name: "Rands Leadership Slack",
    platform: Platform.SLACK,
    url: "https://randsinrepose.com/welcome-to-rands-leadership-slack/",
    audienceDesc: "~30k engineering leaders & managers",
    rules: "Invite-only Slack for engineering leaders; you must email to join and accept the Code of Conduct. Overt self-promotion and marketing are strongly frowned upon and there is no showcase channel — participate genuinely, don't pitch. Spamming links risks removal.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings (US)",
    tags: ["technical", "founders", "startup", "product", "community"],
  },
  {
    slug: "discord-indie-hackers",
    name: "Indie Hackers Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/sSHq2rAz",
    audienceDesc: "~10k indie founders, makers & entrepreneurs",
    rules: "Community for founders and indie hackers to connect, find co-founders, and share projects. Self-promotion is welcomed in the dedicated share-your-project/self-promo channels; keep pitches out of general discussion. Verify the current invite from indiehackers.com.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in the share-your-project channel",
    tags: ["founders", "indie", "makers", "startup", "saas", "product", "community"],
  },
  {
    slug: "discord-svelte",
    name: "Svelte Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/svelte",
    audienceDesc: "~66k Svelte developers",
    rules: "Official Svelte community server for help and discussion. Share projects in the dedicated show-and-tell/#projects channel; posting product or marketing links in help channels is treated as spam. Read #rules on join.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in the show-and-tell channel",
    tags: ["developers", "frontend", "webdev", "javascript", "svelte", "community"],
  },
  {
    slug: "discord-nuxt",
    name: "Nuxt Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/nuxt",
    audienceDesc: "~31k Nuxt & Vue developers",
    rules: "Official Nuxt community server for announcements, releases, and support. Share what you build in the dedicated showcase channel; keep help and general channels free of promotional links.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in the showcase channel",
    tags: ["developers", "frontend", "webdev", "javascript", "vue", "community"],
  },
  {
    slug: "discord-elixir",
    name: "Elixir Language Discord",
    platform: Platform.DISCORD,
    url: "https://discord.gg/elixir",
    audienceDesc: "~20k Elixir developers",
    rules: "Community server for the Elixir language focused on help and discussion. Share projects in the dedicated libraries/showcase channel; avoid dropping product or marketing links in general and help channels. Follow the code of conduct.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime in the showcase channel",
    tags: ["developers", "backend", "technical", "opensource", "elixir", "community"],
  },
];
