import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";
import {
  HN_READINESS,
  HN_SHOW_READINESS,
  PRODUCT_HUNT_READINESS,
  INDIE_HACKERS_READINESS,
  DEVTO_READINESS,
  HASHNODE_READINESS,
  LOBSTERS_READINESS,
  X_READINESS,
  LINKEDIN_READINESS,
  WIP_READINESS,
  BETALIST_READINESS,
  redditReadiness,
} from "./requirements";

/** The original hand-authored core catalog (HN, top subreddits, PH, IH, blogs, X/LI). */
export const core: Seed[] = [
  {
    slug: "hn-show",
    name: "Hacker News — Show HN",
    platform: Platform.HACKERNEWS,
    url: "https://news.ycombinator.com/show",
    audienceDesc: "~5M developers & founders · very high intent",
    rules:
      "Show HN is for something you built that people can try. Lead with the problem and the build story, not marketing. No hype adjectives. Reply to every comment. Title format: 'Show HN: <what it is>'.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue–Thu 8am ET",
    tags: [
      "developers",
      "devtools",
      "infra",
      "technical",
      "launch",
      "opensource",
      "api",
      "backend",
      "startup",
    ],
    accountRequirements: HN_SHOW_READINESS,
  },
  {
    slug: "hn",
    name: "Hacker News",
    platform: Platform.HACKERNEWS,
    url: "https://news.ycombinator.com",
    audienceDesc: "front page · technical, skeptical, high reach",
    rules:
      "Submit a link (blog post, writeup) — not a pitch. Substance wins; titles must be factual, no clickbait. Best for deep technical writeups and launches with a story.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue–Thu 8am ET",
    tags: [
      "developers",
      "technical",
      "blog",
      "writeup",
      "infra",
      "backend",
      "security",
      "opensource",
    ],
    accountRequirements: HN_READINESS,
  },
  {
    slug: "product-hunt",
    name: "Product Hunt",
    platform: Platform.PRODUCTHUNT,
    url: "https://www.producthunt.com",
    audienceDesc: "makers, early adopters, PMs",
    rules:
      "Launch goes live 00:01 PT and runs 24h. Prepare assets (gallery, first comment, maker story) ahead. Rally your network early; don't buy upvotes (grounds for removal). One clear tagline.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue 00:01 PT",
    tags: [
      "launch",
      "product",
      "saas",
      "devtools",
      "makers",
      "startup",
      "b2b",
    ],
    accountRequirements: PRODUCT_HUNT_READINESS,
  },
  {
    slug: "indie-hackers",
    name: "Indie Hackers — Show IH",
    platform: Platform.INDIEHACKERS,
    url: "https://www.indiehackers.com",
    audienceDesc: "warm founder & bootstrapper community",
    rules:
      "Posting is gated: a fresh account can't create posts until IH grants privileges — earn them with authentic, effortful comments over a week or two first (or unlock via IH Plus). Once in: value-first, share what you built and the numbers (revenue, users, lessons). Transparency is rewarded; pure promotion is ignored. Engage in the comments.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekday mornings",
    tags: [
      "founders",
      "indie",
      "saas",
      "startup",
      "product",
      "b2b",
      "makers",
    ],
    accountRequirements: INDIE_HACKERS_READINESS,
  },
  {
    slug: "r-webdev",
    name: "r/webdev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/webdev",
    audienceDesc: "2.6M members · web developers",
    rules:
      "Strict 90/10 self-promo rule: 9 value posts per 1 promo. No links in titles. Showoff Saturday for projects. Frame as a guide/lesson, mention the tool as context only.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Mon/Wed 9am ET",
    tags: ["webdev", "frontend", "javascript", "developers", "api", "devtools"],
    accountRequirements: redditReadiness(),
  },
  {
    slug: "r-saas",
    name: "r/SaaS",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/SaaS",
    audienceDesc: "SaaS founders & operators",
    rules:
      "Heavily moderated for self-promo. Share lessons/metrics, not pitches. Direct product links often removed. Read the rules; a removed post can hurt account standing.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Tue–Thu 10am ET",
    tags: ["saas", "founders", "b2b", "startup", "product"],
    accountRequirements: redditReadiness({
      minAccountAgeDays: 60,
      minKarma: 250,
      extraTips: ["Share metrics/lessons, not a pitch — direct product links are often removed."],
    }),
  },
  {
    slug: "r-programming",
    name: "r/programming",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/programming",
    audienceDesc: "6M+ · general programming, skeptical",
    rules:
      "Technical articles only, no product promotion. Self-promo is quickly removed and downvoted. Only submit a genuinely substantive writeup that stands on its own.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: [
      "developers",
      "technical",
      "blog",
      "writeup",
      "backend",
      "opensource",
    ],
    accountRequirements: redditReadiness({
      minAccountAgeDays: 60,
      minKarma: 250,
      extraTips: ["Only a genuinely substantive writeup survives here — no product promotion."],
    }),
  },
  {
    slug: "r-devops",
    name: "r/devops",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/devops",
    audienceDesc: "SRE / platform / infra engineers",
    rules:
      "Practitioners dislike ads. Share an operational lesson or architecture; tool mention as a footnote. No link-in-title. Genuine discussion of failure modes lands well.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Tue–Thu 9am ET",
    tags: ["devops", "infra", "backend", "developers", "security", "api"],
    accountRequirements: redditReadiness(),
  },
  {
    slug: "r-selfhosted",
    name: "r/selfhosted",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/selfhosted",
    audienceDesc: "self-hosting & open-source enthusiasts",
    rules:
      "Open-source / self-hostable tools welcomed if you're transparent. Show a real setup and screenshots. Closed-source SaaS gets a colder reception — be upfront about pricing.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekend mornings",
    tags: ["selfhosted", "opensource", "infra", "devtools", "developers"],
    accountRequirements: redditReadiness({
      extraTips: ["Show a real setup with screenshots; be upfront if it's closed-source or paid."],
    }),
  },
  {
    slug: "r-node",
    name: "r/node",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/node",
    audienceDesc: "Node.js developers",
    rules:
      "Node-specific technical content. Self-promo tolerated if genuinely useful and clearly relevant to Node. Explain the how, not just the what.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["node", "javascript", "backend", "developers", "api", "webhooks"],
    accountRequirements: redditReadiness(),
  },
  {
    slug: "r-javascript",
    name: "r/javascript",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/javascript",
    audienceDesc: "1.9M · JS developers",
    rules:
      "Showoff posts restricted to weekly threads; standalone promo removed. Must be substantive JS content. Very sensitive to marketing tone.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["javascript", "frontend", "node", "developers", "webdev"],
    accountRequirements: redditReadiness({
      minAccountAgeDays: 60,
      minKarma: 250,
      extraTips: ["Showoff posts belong in the weekly thread; standalone promo is removed."],
    }),
  },
  {
    slug: "r-startups",
    name: "r/startups",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/startups",
    audienceDesc: "founders & early operators",
    rules:
      "Promotion only in the weekly 'Share Your Startup' thread. Elsewhere, contribute advice/lessons. Direct launches outside the thread are removed.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["startup", "founders", "saas", "product", "b2b"],
    accountRequirements: redditReadiness({
      extraTips: ["Promotion only lands in the weekly 'Share Your Startup' thread."],
    }),
  },
  {
    slug: "r-entrepreneur",
    name: "r/Entrepreneur",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/Entrepreneur",
    audienceDesc: "broad entrepreneur audience",
    rules:
      "No direct promotion; share the journey and lessons. Less technical crowd — frame benefits in business terms. Links often flagged.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["founders", "startup", "saas", "b2b", "product"],
    accountRequirements: redditReadiness(),
  },
  {
    slug: "dev-to",
    name: "dev.to",
    platform: Platform.DEVTO,
    url: "https://dev.to",
    audienceDesc: "developer blogging community",
    rules:
      "Publish a genuine technical article (tutorial, walkthrough, retro). Product mention fine if the post teaches something. Use tags (#webdev, #node). Canonical-URL your own blog.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Any weekday morning",
    tags: [
      "blog",
      "writeup",
      "developers",
      "webdev",
      "javascript",
      "node",
      "devtools",
      "technical",
    ],
    accountRequirements: DEVTO_READINESS,
  },
  {
    slug: "hashnode",
    name: "Hashnode",
    platform: Platform.DEVTO,
    url: "https://hashnode.com",
    audienceDesc: "developer blogging network",
    rules:
      "Technical writing platform with a dev community. Long-form tutorials and engineering deep-dives perform best. Own your domain via the mapped blog.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Any weekday",
    tags: ["blog", "writeup", "developers", "technical", "backend", "webdev"],
    accountRequirements: HASHNODE_READINESS,
  },
  {
    slug: "lobsters",
    name: "Lobste.rs",
    platform: Platform.LOBSTERS,
    url: "https://lobste.rs",
    audienceDesc: "invite-only · high-signal technical crowd",
    rules:
      "Invite-only; tightly moderated. Only deep technical content, tagged correctly. Self-promo must be disclosed and is discouraged unless genuinely notable. No marketing whatsoever.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Invite only",
    tags: [
      "developers",
      "technical",
      "writeup",
      "infra",
      "backend",
      "security",
      "opensource",
    ],
    accountRequirements: LOBSTERS_READINESS,
  },
  {
    slug: "x",
    name: "X (Twitter)",
    platform: Platform.X,
    url: "https://x.com",
    audienceDesc: "dev-Twitter, build-in-public founders",
    rules:
      "Hook in the first line, link last (or in a reply — links can suppress reach). Thread format for features. Post Tue–Thu mornings. Engage replies fast for the algorithm.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue–Thu 9am ET",
    tags: [
      "founders",
      "developers",
      "indie",
      "startup",
      "product",
      "launch",
      "saas",
    ],
    accountRequirements: X_READINESS,
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    platform: Platform.LINKEDIN,
    url: "https://www.linkedin.com",
    audienceDesc: "B2B buyers, professional network",
    rules:
      "Put the link in the first comment — LinkedIn throttles posts with outbound links. Lead with a personal/professional angle. Business value framing beats technical detail.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue–Thu 8–10am local",
    tags: ["b2b", "saas", "founders", "product", "startup"],
    accountRequirements: LINKEDIN_READINESS,
  },
  {
    slug: "wip",
    name: "WIP",
    platform: Platform.INDIEHACKERS,
    url: "https://wip.co",
    audienceDesc: "maker community shipping in public",
    rules:
      "Access is gated: WIP is invite-only — join free with an invite from an existing member, or pay for membership otherwise (price shown at Stripe checkout). Once in: log what you shipped as a completed todo; makers follow along. Friendly to frequent small updates. Value-first, low pressure.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Any day",
    tags: ["makers", "indie", "founders", "product", "startup", "launch"],
    accountRequirements: WIP_READINESS,
    cost: { type: "freemium", note: "invite-only; free with an invite, else paid membership" },
  },
  {
    slug: "betalist",
    name: "BetaList",
    platform: Platform.OTHER,
    url: "https://betalist.com",
    audienceDesc: "early-adopter directory for pre-launch startups",
    rules:
      "For early-stage startups seeking first users. Submission is paid-only (from $39; the $99 tier also features you by Monday and includes the ~70k-subscriber newsletter). Cheapest tier is featured within ~2 weeks; full refund if you're not selected. One-time exposure — best for an initial launch, not every ship.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["launch", "startup", "saas", "product", "b2b"],
    accountRequirements: BETALIST_READINESS,
    cost: { type: "paid", note: "from $39" },
  },
];
