import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";
import {
  ALTERNATIVETO_READINESS,
  SAASHUB_READINESS,
  SETAPP_READINESS,
} from "./requirements";

/** Product/startup/software directories & launch platforms (built for listing). */
export const directories: Seed[] = [
  {
    slug: "dir-alternativeto",
    name: "AlternativeTo",
    platform: Platform.DIRECTORY,
    url: "https://alternativeto.net/",
    audienceDesc: "software discovery · high buyer intent",
    rules: "Sign in and use \"Suggest new application\" under the user menu, filling platforms, license, description and tags. New accounts must wait one week before submitting a new app page; edits are community-verified and approved when reviewed.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "software", "product", "saas", "showcase", "b2b"],
    accountRequirements: ALTERNATIVETO_READINESS,
  },
  {
    slug: "dir-saashub",
    name: "SaaSHub",
    platform: Platform.DIRECTORY,
    url: "https://www.saashub.com/services/submit",
    audienceDesc: "SaaS discovery · alternatives & reviews",
    rules: "Submit product name, tagline, categories and rivals via the submit form; verification requires an email address on the product's domain. Free listings are typically approved within one to two days.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "saas", "software", "b2b", "product", "startup"],
    accountRequirements: SAASHUB_READINESS,
  },
  {
    slug: "dir-uneed",
    name: "Uneed",
    platform: Platform.DIRECTORY,
    url: "https://www.uneed.best/submit-a-tool",
    audienceDesc: "indie product launches · daily competition",
    rules: "Paste your product URL to prefill the listing, then sign up to save it and join the free launch queue. Free submissions get an automatic next-available slot; \"Skip the Line\" (from $29.99) lets you choose your own launch date. Every listing gets a do-follow backlink.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Rolling (pick launch date)",
    tags: ["directory", "launch", "indie", "makers", "product", "startup"],
    cost: { type: "freemium", note: "free queue; skip-the-line from $29.99" },
  },
  {
    slug: "dir-peerlist",
    name: "Peerlist Launchpad",
    platform: Platform.DIRECTORY,
    url: "https://peerlist.io/projects",
    audienceDesc: "builder network · weekly launch spotlight",
    rules: "Add the project to your Peerlist profile with all mandatory fields (name, tagline, cover image, demo link), then launch it from the weekly Spotlight banner. Launches open only on Mondays, 00:00-23:59 UTC.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Mondays (UTC)",
    tags: ["directory", "launch", "makers", "developers", "product", "founders"],
  },
  {
    slug: "dir-devhunt",
    name: "DevHunt",
    platform: Platform.DIRECTORY,
    url: "https://devhunt.org/",
    audienceDesc: "developer tools · built by developers",
    rules: "Sign in with GitHub and submit your dev tool with description, screenshots and links; GitHub auth keeps listings tied to real makers. Free, open-source and community-voted with weekly winners.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Rolling (weekly)",
    tags: ["directory", "devtools", "developers", "technical", "launch", "opensource"],
  },
  {
    slug: "dir-microlaunch",
    name: "MicroLaunch",
    platform: Platform.DIRECTORY,
    url: "https://microlaunch.net/",
    audienceDesc: "indie products · month-long visibility",
    rules: "Sign up, complete your profile and submit your product with description, screenshots and founder story; free launches are auto-distributed across SEO pages. A paid Pro Launch (from $39) adds queue skip, featured boosts, Product of the Day placement and a do-follow backlink.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Rolling",
    tags: ["directory", "launch", "indie", "makers", "product", "startup"],
    cost: { type: "freemium", note: "free launch; Pro from $39" },
  },
  {
    slug: "dir-fazier",
    name: "Fazier",
    platform: Platform.DIRECTORY,
    url: "https://fazier.com/submit",
    audienceDesc: "indie product launches · daily feed",
    rules: "Use the submit form to add your product with details, description and assets like screenshots or a logo. The free listing is reviewed and listed within ~15 days and requires a backlink to Fazier; paid tiers (from $19) publish immediately, drop the backlink requirement and add homepage featuring.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Rolling",
    tags: ["directory", "launch", "indie", "makers", "product", "startup"],
    cost: { type: "freemium", note: "free (backlink, ~15-day review); paid from $19" },
  },
  {
    slug: "dir-theresanaiforthat",
    name: "There's An AI For That",
    platform: Platform.DIRECTORY,
    url: "https://theresanaiforthat.com/launch/",
    audienceDesc: "AI tool discovery · large AI audience",
    rules: "Submit your AI tool via the launch page with its URL and details; all submissions go through editorial approval, typically processed in one to two days.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "ai", "ml", "product", "launch", "showcase"],
  },
  {
    slug: "dir-stackshare",
    name: "StackShare",
    platform: Platform.DIRECTORY,
    url: "https://stackshare.io/tools/new",
    audienceDesc: "dev tech-stack discovery · engineering audience",
    rules: "Use the \"List a Tool\" flow to add name, website, category/layer and GitHub or docs links, or claim an existing tool page and verify via company email or GitHub. New listings may pass a short review.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "devtools", "developers", "technical", "cloud", "api"],
  },
  {
    slug: "dir-slant",
    name: "Slant",
    platform: Platform.DIRECTORY,
    url: "https://www.slant.co/",
    audienceDesc: "\"best X\" product recommendations · comparison intent",
    rules: "Find a relevant question, use the \"I Recommend\" button to add your product as an option, then add pros and supporting detail. Community-curated; recommendations are ranked by votes rather than a formal queue.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime",
    tags: ["directory", "product", "software", "developers", "showcase", "saas"],
  },
  {
    slug: "dir-launching-next",
    name: "Launching Next",
    platform: Platform.DIRECTORY,
    url: "https://www.launchingnext.com/submit/",
    audienceDesc: "early-stage startup directory · newsletter reach",
    rules: "Submit your startup through the form with name, URL and description; submissions are moderated daily and you're emailed if published. Free listing, or a paid upgrade for review within one business day.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "startup", "founders", "launch", "product", "showcase"],
    cost: { type: "freemium", note: "free listing; paid upgrade for 1-business-day review" },
  },
  {
    slug: "dir-startup-stash",
    name: "Startup Stash",
    platform: Platform.DIRECTORY,
    url: "https://startupstash.com/",
    audienceDesc: "curated startup tools & resources · founder audience",
    rules: "Create a free account and complete the submission form with accurate details about your tool or resource. The directory is curated, so listings are selective and reviewed before appearing.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "startup", "founders", "product", "saas", "growth"],
  },
  {
    slug: "dir-betapage",
    name: "BetaPage",
    platform: Platform.DIRECTORY,
    url: "https://betapage.co/submit-startup",
    audienceDesc: "early adopters · beta & new startup discovery",
    rules: "Submit your startup for free at any stage (in development, beta or live) via the submit-startup form. Lead the description with an exclusivity or early-access hook for this early-adopter community.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "startup", "launch", "product", "founders", "showcase"],
  },
  {
    slug: "dir-sideprojectors",
    name: "SideProjectors",
    platform: Platform.DIRECTORY,
    url: "https://www.sideprojectors.com/",
    audienceDesc: "side-project marketplace · makers buying & showcasing",
    rules: "Enter your project's homepage URL to auto-populate the listing, then submit to sell, find a co-founder, or showcase. Every project is moderator-reviewed before going live; complete listings are approved fastest.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "indie", "makers", "product", "showcase", "startup"],
  },
  {
    slug: "dir-futurepedia",
    name: "Futurepedia",
    platform: Platform.DIRECTORY,
    url: "https://www.futurepedia.io/submit-tool",
    audienceDesc: "AI tools directory · professional audience",
    rules: "Submit your AI tool or software through the submit-tool page by providing its URL and details. All submissions are subject to editorial approval before listing.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (queued)",
    tags: ["directory", "ai", "ml", "product", "saas", "showcase"],
  },
  {
    slug: "dir-g2",
    name: "G2",
    platform: Platform.DIRECTORY,
    url: "https://www.g2.com/products/new",
    audienceDesc: "software reviews · high buyer intent · enterprise",
    rules: "Add or claim your product profile, then complete vendor verification; G2's research team reviews and conditionally approves submissions, verifying category and details over roughly 3-5 business days.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Anytime (queued)",
    tags: ["directory", "saas", "b2b", "software", "product", "marketing"],
  },

  // ── Vertical pack: Mac / desktop ─────────────────────────────────
  {
    slug: "dir-macmenubar",
    name: "MacMenuBar",
    platform: Platform.DIRECTORY,
    url: "https://macmenubar.com/submit-your-menu-bar-app/",
    audienceDesc: "curated directory of 1,400+ macOS menu bar apps · Mac power-user discovery",
    rules: "A human-curated directory of true macOS menu bar apps. Submit via the 'Submit your menu bar app' form; the menu bar must be central to the app's experience (non–menu-bar apps are rejected). Search the directory first to confirm it isn't already listed, and expect owner/editorial review before it goes live.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (curated)",
    tags: ["directory", "macos", "desktop", "software", "showcase"],
  },
  {
    slug: "dir-setapp",
    name: "Setapp",
    platform: Platform.DIRECTORY,
    url: "https://setapp.com/developers",
    audienceDesc: "MacPaw's curated Mac/iOS app subscription bundle · distribution to Setapp subscribers",
    rules: "A curated subscription marketplace, not a forum: developers apply to get an app in. The path is apply → MacPaw technical/quality review (apply only if you're confident in the app's quality) → integrate the Setapp SDK → launch. There's no upfront fee; revenue is a usage-based share (Setapp Membership ~70/30; a Single-App option is 85/15).",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Anytime (application + review)",
    tags: ["directory", "macos", "desktop", "software", "product"],
    accountRequirements: SETAPP_READINESS,
  },
];
