import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";

/** Developer/startup newsletters that accept submissions or feature launches. */
export const newsletters: Seed[] = [
  {
    slug: "news-tldr",
    name: "TLDR Newsletter",
    platform: Platform.NEWSLETTER,
    url: "https://tldr.tech/",
    audienceDesc: "~7M+ subscribers · daily byte-sized tech digest",
    rules: "Editorial links are hand-curated from the day's biggest tech stories; there is no open link form, so earning a spot means being genuinely newsworthy. Paid sponsor slots are available separately via advertise.tldr.tech (max 3 per issue, copy written in TLDR's voice).",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Daily (weekday mornings)",
    tags: ["newsletter", "developers", "technical", "devtools", "startup", "ai", "launch"],
  },
  {
    slug: "news-hackernewsletter",
    name: "Hacker Newsletter",
    platform: Platform.NEWSLETTER,
    url: "https://hackernewsletter.com/",
    audienceDesc: "~60k subscribers · weekly best of Hacker News",
    rules: "Links are hand-picked by the editor from the week's top Hacker News posts, so the reliable path in is to do well on HN itself. No public submission form; editorial discretion only.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekly (Friday)",
    tags: ["newsletter", "developers", "startup", "technical", "founders", "opensource"],
  },
  {
    slug: "news-consoledev",
    name: "Console.dev",
    platform: Platform.NEWSLETTER,
    url: "https://console.dev/",
    audienceDesc: "~30k+ developers · weekly devtools reviews",
    rules: "Reviews 2-3 developer tools each week; submit yours via the tool form on the site. Must be built for developers with self-service signup (no sales gate) and genuinely useful in the dev workflow per their published selection criteria.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (published Thursdays)",
    tags: ["newsletter", "devtools", "developers", "technical", "opensource", "launch"],
  },
  {
    slug: "news-javascriptweekly",
    name: "JavaScript Weekly",
    platform: Platform.NEWSLETTER,
    url: "https://javascriptweekly.com/link",
    audienceDesc: "~150k+ JS developers · weekly curated links",
    rules: "Cooper Press accepts direct link suggestions via the submission form; editor Peter Cooper curates final picks. Favor substantive articles, releases and tools over pure marketing; original or exclusive content is preferred.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Friday)",
    tags: ["newsletter", "javascript", "frontend", "webdev", "developers", "node"],
  },
  {
    slug: "news-nodeweekly",
    name: "Node Weekly",
    platform: Platform.NEWSLETTER,
    url: "https://nodeweekly.com/link",
    audienceDesc: "~80k+ Node.js developers · weekly curated links",
    rules: "Cooper Press sister publication to JavaScript Weekly; suggest links through the form and the editor curates. Node.js-relevant articles, releases and libraries do best.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Wednesday)",
    tags: ["newsletter", "node", "javascript", "backend", "developers", "opensource"],
  },
  {
    slug: "news-reactstatus",
    name: "React Status",
    platform: Platform.NEWSLETTER,
    url: "https://react.statuscode.com/link",
    audienceDesc: "~40k+ React developers · weekly curated links",
    rules: "Cooper Press newsletter for the React ecosystem; submit links via the form for editorial review. React, React Native and related tooling/releases are in scope.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Wednesday)",
    tags: ["newsletter", "react", "frontend", "javascript", "webdev", "developers"],
  },
  {
    slug: "news-frontendfocus",
    name: "Frontend Focus",
    platform: Platform.NEWSLETTER,
    url: "https://frontendfoc.us/link",
    audienceDesc: "~50k+ frontend developers · weekly curated links",
    rules: "Cooper Press newsletter covering HTML, CSS, browser APIs and frontend tooling; suggest links via the form for editorial curation. Prefer practical articles and tool releases over promos.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Wednesday)",
    tags: ["newsletter", "frontend", "webdev", "javascript", "developers", "devtools"],
  },
  {
    slug: "news-rubyweekly",
    name: "Ruby Weekly",
    platform: Platform.NEWSLETTER,
    url: "https://rubyweekly.com/link",
    audienceDesc: "~60k+ Ruby developers · weekly curated links",
    rules: "Cooper Press newsletter for Ruby and Rails; submit links via the form for the editor to review. Ruby/Rails articles, gems and releases are the sweet spot.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Thursday)",
    tags: ["newsletter", "ruby", "backend", "developers", "webdev", "opensource"],
  },
  {
    slug: "news-golangweekly",
    name: "Golang Weekly",
    platform: Platform.NEWSLETTER,
    url: "https://golangweekly.com/link",
    audienceDesc: "~40k+ Go developers · weekly curated links",
    rules: "Cooper Press newsletter for the Go ecosystem; suggest links through the form and the editor curates. Go articles, libraries and release notes are welcome.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Friday)",
    tags: ["newsletter", "golang", "backend", "developers", "opensource", "infra"],
  },
  {
    slug: "news-bytes",
    name: "Bytes (JavaScript)",
    platform: Platform.NEWSLETTER,
    url: "https://bytes.dev/",
    audienceDesc: "~200k+ subscribers · twice-weekly JS digest",
    rules: "Written by ui.dev (Tyler McGinnis); links are hand-picked by the authors with no open submission form, so relevance and quality earn a mention. Sponsor slots available via the advertise page.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Twice weekly (Mon & Thu)",
    tags: ["newsletter", "javascript", "frontend", "webdev", "developers", "typescript"],
  },
  {
    slug: "news-pythonweekly",
    name: "Python Weekly",
    platform: Platform.NEWSLETTER,
    url: "https://www.pythonweekly.com/",
    audienceDesc: "~100k+ Python developers · weekly curated links",
    rules: "Free weekly curation of Python news, articles, releases and jobs; email the editor to suggest a link or project. Editor selects at their discretion, favoring substantive Python content.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekly (Thursday)",
    tags: ["newsletter", "python", "developers", "data", "backend", "opensource"],
  },
  {
    slug: "news-pycoders",
    name: "PyCoder's Weekly",
    platform: Platform.NEWSLETTER,
    url: "https://pycoders.com/submissions",
    audienceDesc: "~100k+ Python developers · weekly curated links",
    rules: "Open submissions form for articles, projects and news; the team reviews and curates each issue. Python-relevant tutorials, releases and tools are a strong fit.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Wednesday)",
    tags: ["newsletter", "python", "developers", "opensource", "data", "technical"],
  },
  {
    slug: "news-lastweekinaws",
    name: "Last Week in AWS",
    platform: Platform.NEWSLETTER,
    url: "https://www.lastweekinaws.com/",
    audienceDesc: "~30k+ cloud engineers · weekly AWS news with snark",
    rules: "Corey Quinn curates AWS news, tools and blog posts each week; there is no open form, so genuinely useful cloud/AWS tooling is what gets noticed. Editorial discretion only.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekly (Monday AM PT)",
    tags: ["newsletter", "cloud", "devops", "infra", "developers", "aws"],
  },
  {
    slug: "news-tldr-ai",
    name: "TLDR AI",
    platform: Platform.NEWSLETTER,
    url: "https://tldr.tech/ai",
    audienceDesc: "~1.1M subscribers · daily AI news & tools digest",
    rules: "Editor-curated summaries of model releases, research and new AI tools; no public link form, so coverage is earned by being newsworthy. Sponsor placements available via advertise.tldr.tech.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Daily (weekdays)",
    tags: ["newsletter", "ai", "ml", "developers", "technical", "devtools", "launch"],
  },
  {
    slug: "news-bensbites",
    name: "Ben's Bites",
    platform: Platform.NEWSLETTER,
    url: "https://www.bensbites.com/",
    audienceDesc: "~100k+ subscribers · AI news for builders & founders",
    rules: "Daily AI roundup with a builder/founder lens that has a track record of surfacing new AI tools early; curated by the team with no open form. Pitch via their contact/sponsor channels; editorial coverage is discretionary.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Daily (weekdays)",
    tags: ["newsletter", "ai", "startup", "founders", "product", "launch", "saas"],
  },
  {
    slug: "news-changelog",
    name: "Changelog News",
    platform: Platform.NEWSLETTER,
    url: "https://changelog.com/news/submit",
    audienceDesc: "Thousands of developers · weekly dev news + podcast",
    rules: "Open submission at changelog.com/news/submit: sign in and share any project, article or link (yours or not). Accepted items can appear in Changelog News, the homepage and Changelog Weekly.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekly (Monday)",
    tags: ["newsletter", "developers", "opensource", "devtools", "technical", "launch"],
  },
];
