import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";
import {
  MEDIUM_READINESS,
  HACKERNOON_READINESS,
  SUBSTACK_READINESS,
  FCC_NEWS_READINESS,
  DZONE_READINESS,
} from "./requirements";

/** Blogging platforms, dev-heavy social networks, and technical forums. */
export const social: Seed[] = [
  {
    slug: "medium",
    name: "Medium",
    platform: Platform.BLOG,
    url: "https://medium.com",
    audienceDesc: "Broad general and tech readership; strong distribution for tutorials, engineering deep-dives, and founder stories via curated publications.",
    rules: "First-party promotion is allowed — you may link to your own product, site, or mailing list — but third-party ads and posts that exist only to drive traffic are treated as spam. Lead with a genuinely useful writeup and keep any product mention to a short call-to-action at the end; disclose affiliate links per FTC rules.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue-Thu, 9-11am ET",
    tags: ["developers", "technical", "blog", "writeup", "startup", "product"],
    accountRequirements: MEDIUM_READINESS,
  },
  {
    slug: "hackernoon",
    name: "HackerNoon",
    platform: Platform.BLOG,
    url: "https://hackernoon.com",
    audienceDesc: "Large technology and startup audience; editor-reviewed stories on software, AI, crypto, and building companies.",
    rules: "Anyone can submit; staff editors review within ~3 business days and reject overtly promotional, corporate 'we'-voice pieces. Tell a first-person story about what you built, disclose any company you have a stake in, and meet the minimum word count rather than pitching your product.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue-Wed, 8-10am ET",
    tags: ["developers", "technical", "startup", "ai", "blog", "writeup"],
    accountRequirements: HACKERNOON_READINESS,
  },
  {
    slug: "substack",
    name: "Substack",
    platform: Platform.BLOG,
    url: "https://substack.com",
    audienceDesc: "Your own subscription newsletter plus the Substack network and Notes; technology is one of the platform's largest categories, home to engineering and system-design writers.",
    rules: "You own the publication, so self-promotion is fully allowed — the constraint is your subscribers' patience, not a moderator. Publish a real technical essay or launch note and use Notes and the recommendations network to reach beyond your list; hard-selling every post churns readers.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Tue/Thu, 7-9am ET",
    tags: ["developers", "technical", "blog", "writeup", "founders", "saas"],
    accountRequirements: SUBSTACK_READINESS,
  },
  {
    slug: "freecodecamp-news",
    name: "freeCodeCamp News",
    platform: Platform.BLOG,
    url: "https://www.freecodecamp.org/news",
    audienceDesc: "Huge audience of learners and working developers; high-authority publication for tutorials and technical explainers.",
    rules: "Contribute via a Hashnode account and email editorial for an invite; drafts are editorially reviewed. A single call-to-action for your product at the end of a tutorial is fine, but opening with a product link, using non-self-authored affiliate links, or submitting paid placements without disclosure gets rejected.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Mon-Wed, 9am-12pm ET",
    tags: ["developers", "technical", "webdev", "javascript", "blog", "writeup"],
    accountRequirements: FCC_NEWS_READINESS,
  },
  {
    slug: "dzone",
    name: "DZone",
    platform: Platform.BLOG,
    url: "https://dzone.com",
    audienceDesc: "Professional software-development audience across Java, DevOps, cloud, databases, and architecture.",
    rules: "Submissions must teach software professionals something original — DZone explicitly rejects content whose intent is to advertise a product, company-branded profiles, and AI-generated articles. Write a vendor-neutral technical piece under your real name and job title; mention tools only as incidental examples, not the pitch.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Tue-Thu, 8-10am ET",
    tags: ["developers", "technical", "backend", "devtools", "blog", "writeup"],
    accountRequirements: DZONE_READINESS,
  },
  {
    slug: "mastodon-fosstodon",
    name: "Fosstodon",
    platform: Platform.MASTODON,
    url: "https://fosstodon.org",
    audienceDesc: "Invite-friendly Mastodon instance for people into technology and free & open-source software.",
    rules: "Posting your own projects is welcomed — 'toot your own horn' — but link-only posts, hashtag stuffing, and repetitive for-profit self-promotion are treated as spam. Share the launch conversationally with context and stay to engage; don't drive-by drop a bare link.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekdays, 9-11am ET",
    tags: ["developers", "opensource", "technical", "devtools", "community", "makers"],
  },
  {
    slug: "mastodon-hachyderm",
    name: "Hachyderm",
    platform: Platform.MASTODON,
    url: "https://hachyderm.io",
    audienceDesc: "Curated Mastodon instance of tech-industry professionals; strong SRE, infrastructure, and engineering presence.",
    rules: "Company, business, and project accounts are restricted or invite-only — post as a real person, not a brand. Share your work authentically with genuine engagement; the moderated 'don't be a jerk' culture and the personal-account rule mean corporate broadcast posts don't fit.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekdays, 10am-1pm ET",
    tags: ["developers", "technical", "backend", "security", "opensource", "community"],
  },
  {
    slug: "bluesky",
    name: "Bluesky",
    platform: Platform.BLUESKY,
    url: "https://bsky.app",
    audienceDesc: "Fast-growing open social network with a large developer, open-source, and indie-maker presence built on the AT Protocol.",
    rules: "No formal anti-self-promo rule — you post to your own followers and via custom feeds — so norms are cultural: mix build-in-public updates and genuine replies with launch posts. Pure promo with no engagement underperforms; use relevant tech feeds and threads rather than one bare announcement.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekdays, 9am-12pm ET",
    tags: ["developers", "indie", "makers", "opensource", "community", "launch"],
  },
  {
    slug: "designer-news",
    name: "Designer News",
    platform: Platform.FORUM,
    url: "https://www.designernews.co",
    audienceDesc: "Community of designers and design-minded technologists sharing links, tools, and product launches.",
    rules: "The community expects mature behavior and high-quality submissions and bans liberally, so self-serving link drops are risky. Post genuinely relevant design or product-craft content, participate in comments, and frame a launch around the design story rather than pure marketing.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Tue-Thu, 10am-1pm ET",
    tags: ["design", "product", "makers", "community", "showcase", "launch"],
  },
  {
    slug: "ministry-of-testing",
    name: "Ministry of Testing — The Club",
    platform: Platform.FORUM,
    url: "https://club.ministryoftesting.com",
    audienceDesc: "Global community of software testers, QA, and quality engineers discussing tools and practices.",
    rules: "The Club explicitly prohibits direct or indirect promotion of commercial testing tools, services, or training. If your product is testing-related, don't post it as a launch — instead contribute real expertise in discussions and let a genuinely helpful profile do the work; overt promotion is removed.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Tue-Thu, 8-11am ET",
    tags: ["developers", "technical", "devtools", "community", "product"],
  },
  {
    slug: "stack-overflow",
    name: "Stack Overflow",
    platform: Platform.FORUM,
    url: "https://stackoverflow.com",
    audienceDesc: "The largest Q&A community for programmers; enormous reach but strictly help-focused, not promotional.",
    rules: "Self-promotion is heavily restricted — answers that primarily advertise a product get flagged, deleted, and can trigger suspension. You may reference your own tool only when it genuinely answers the question, sparingly, and with an explicit disclosure of affiliation; never post a launch as its own thread.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Tue-Thu, 9am-1pm ET",
    tags: ["developers", "technical", "backend", "frontend", "devtools", "community"],
  },
];
