import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";
import { redditReadiness, R_CYBERSECURITY_READINESS, MACAPPS_READINESS } from "./requirements";

/** Niche language/framework/domain subreddits (verified real, promo rules honest). */
export const subreddits: Seed[] = [
  {
    slug: "r-rust",
    name: "r/rust",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/rust/",
    audienceDesc: "~300k Rust developers",
    rules: "Show-and-tell of your own Rust projects is welcome as a self-post, but blatant marketing and low-effort link drops get removed. Lead with the technical story (what you built, how, what's interesting) rather than a sales pitch, and be present to answer questions.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "opensource", "backend", "community", "rust"],
    accountRequirements: redditReadiness(),
  },
  {
    slug: "r-golang",
    name: "r/golang",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/golang/",
    audienceDesc: "~250k Go developers",
    rules: "Sharing your own Go library or tool is allowed if it's genuinely useful and posted as a self-post with context, but pure promotion and paid products get flagged. Explain the problem it solves and engage in the comments.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "opensource", "community", "golang"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Small/new projects (months of effort, one contributor) belong in the weekly 'Small Projects' thread per the project-requirements wiki.",
        "No emoji, engagement hooks, or AI-generated text in project posts — a couple of plain paragraphs on purpose and results.",
      ],
    }),
  },
  {
    slug: "r-python",
    name: "r/Python",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/Python/",
    audienceDesc: "~1.3M Python developers",
    rules: "Project posts must follow the 'Showcase' format with a required 'What My Project Does / Target Audience / Comparison' write-up; low-effort or purely promotional links are removed. There's a weekly thread for smaller shares.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "opensource", "backend", "community", "python"],
    accountRequirements: redditReadiness({
      extraTips: ["Use the required Showcase format (What My Project Does / Target Audience / Comparison)."],
    }),
  },
  {
    slug: "r-django",
    name: "r/django",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/django/",
    audienceDesc: "~130k Django developers",
    rules: "Sharing your own Django project, package, or tutorial is tolerated when it adds value and is clearly relevant, but repeated promotion of a paid product is not. Post as a self-post with technical detail and answer questions.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "python", "django"],
    accountRequirements: redditReadiness({
      extraTips: [
        "The sub's own rules warn: share your work, but participate in other ways too 'or the spam algorithm might get you'.",
      ],
    }),
  },
  {
    slug: "r-reactjs",
    name: "r/reactjs",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/reactjs/",
    audienceDesc: "~400k React developers",
    rules: "Self-promotion and 'I built X' posts are funneled into the pinned weekly 'Show /r/reactjs' thread; standalone promo posts are removed. Share there with a real description and be ready to discuss the code.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly Show thread",
    tags: ["developers", "frontend", "webdev", "javascript", "react", "community"],
    accountRequirements: redditReadiness({
      minAccountAgeDays: 60,
      minKarma: 250,
      extraTips: ["'I built X' posts go in the pinned weekly Show thread; standalone promo is removed."],
    }),
  },
  {
    slug: "r-vuejs",
    name: "r/vuejs",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/vuejs/",
    audienceDesc: "~100k Vue developers",
    rules: "Sharing your own Vue library, tool, or article is allowed if it's on-topic and useful, but low-effort self-promo and spam are removed. Post as a self-post, explain what it does, and engage with feedback.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "frontend", "webdev", "javascript", "vue", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "The sub's rule allows self-promo 'in a tasteful way' — don't flood the feed with your own links.",
      ],
    }),
  },
  {
    slug: "r-sveltejs",
    name: "r/sveltejs",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/sveltejs/",
    audienceDesc: "~55k Svelte developers",
    rules: "Show-and-tell of your own Svelte projects and libraries is welcome when clearly relevant, but pure marketing gets removed. Lead with what you built and why, and take part in the discussion.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "frontend", "webdev", "javascript", "svelte", "community"],
  },
  {
    slug: "r-rails",
    name: "r/rails",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/rails/",
    audienceDesc: "~80k Ruby on Rails developers",
    rules: "Sharing your own gem, tool, or Rails write-up is accepted when it's genuinely useful to Rails devs, but repetitive product promotion is not. Post as a self-post with technical context and answer questions.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "ruby", "rails"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Label AI-assisted content clearly — the sub added a 'no AI slop' rule.",
        "Hiring/job posts go in the biweekly 'Work it Wednesday' thread, not the feed.",
      ],
    }),
  },
  {
    slug: "r-laravel",
    name: "r/laravel",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/laravel/",
    audienceDesc: "~90k Laravel developers",
    rules: "Self-promotion of your own packages or products is limited and must follow the subreddit's promo guidelines (often a designated thread); undisclosed or repeated promo is removed. Disclose that it's yours and provide real value.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "php", "laravel"],
  },
  {
    slug: "r-php",
    name: "r/PHP",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/PHP/",
    audienceDesc: "~170k PHP developers",
    rules: "This is a discussion-focused sub: self-promotion, product launches, and 'check out my thing' posts are heavily restricted and often removed. Share only substantive technical content and disclose any affiliation.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "php", "community"],
  },
  {
    slug: "r-dotnet",
    name: "r/dotnet",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/dotnet/",
    audienceDesc: "~230k .NET developers",
    rules: "Sharing your own open-source library or article is allowed when relevant and useful, but blatant product promotion and spam are removed. Post as a self-post, explain the technical value, and engage.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "dotnet", "csharp", "community"],
  },
  {
    slug: "r-csharp",
    name: "r/csharp",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/csharp/",
    audienceDesc: "~300k C# developers",
    rules: "Self-promotion is restricted and must follow the 90/10 rule; standalone promo and paid-product posts are frequently removed. Share open-source, technically substantive content and disclose that it's yours.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "dotnet", "csharp", "community"],
  },
  {
    slug: "r-java",
    name: "r/java",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/java/",
    audienceDesc: "~450k Java developers",
    rules: "This is a strictly moderated news/discussion sub for experienced Java devs; self-promotion, beginner content, and 'I made X' posts are largely disallowed. Only share high-quality, on-topic technical articles or projects.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "java", "community"],
  },
  {
    slug: "r-androiddev",
    name: "r/androiddev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/androiddev/",
    audienceDesc: "~200k Android developers",
    rules: "App promotion and self-promo are restricted to the weekly threads; standalone 'check out my app' posts are removed. Share libraries or technical write-ups directly, but push app launches into the designated thread.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly promo thread",
    tags: ["developers", "technical", "mobile", "android", "kotlin", "community"],
  },
  {
    slug: "r-iosprogramming",
    name: "r/iOSProgramming",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/iOSProgramming/",
    audienceDesc: "~110k iOS developers",
    rules: "App and self-promotion are funneled into the weekly 'Self Promotion Saturday' thread; promo posts outside it are removed. Share your app or product there and contribute technical value the rest of the week.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Self Promotion Saturday",
    tags: ["developers", "technical", "mobile", "ios", "swift", "community"],
  },
  {
    slug: "r-swift",
    name: "r/swift",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/swift/",
    audienceDesc: "~90k Swift developers",
    rules: "Sharing your own Swift library, tool, or article is allowed when relevant, but app-store marketing and repeated promo are removed. Post as a self-post focused on the code and engage with feedback.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "mobile", "ios", "swift", "community"],
  },
  {
    slug: "r-flutterdev",
    name: "r/FlutterDev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/FlutterDev/",
    audienceDesc: "~180k Flutter developers",
    rules: "Self-promotion is allowed but capped by the 90/10 rule and must be flaired as promotion; spammy or undisclosed promo is removed. Share packages and apps with real context and take part in the community.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "mobile", "flutter", "opensource", "community"],
  },
  {
    slug: "r-gamedev",
    name: "r/gamedev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/gamedev/",
    audienceDesc: "~1.3M game developers",
    rules: "This sub is for development discussion, not marketing: showcasing your game at any stage is banned, and posts that are only a link to a game or social page are a documented ban. Share postmortems, process, and marketing lessons here — launch the game itself on r/indiegames or r/playmygame.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Anytime (discussion only)",
    tags: ["developers", "technical", "gamedev", "makers", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Don't launch the game here — showcasing is banned at any dev stage; write a postmortem or feedback request instead.",
        "Link-only posts to game/social pages 'will result in a ban' per the sub's rules.",
      ],
    }),
  },
  {
    slug: "r-datascience",
    name: "r/datascience",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/datascience/",
    audienceDesc: "~1.5M data scientists",
    rules: "Self-promotion, tool launches, and blog links are tightly moderated and mostly funneled into weekly threads; standalone promo is removed. Share only genuinely useful, non-salesy content and disclose affiliation.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly sticky thread",
    tags: ["developers", "technical", "data", "ml", "python", "community"],
  },
  {
    slug: "r-machinelearning",
    name: "r/MachineLearning",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/MachineLearning/",
    audienceDesc: "~3M ML researchers & engineers",
    rules: "A research-focused sub: promotion of paid products is not permitted, and a project link passes only when the post offers real substance and invites discussion. Coordinated marketing or SEO posts mean a permanent ban with your history purged; bare paper links without commentary are removed.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "ml", "ai", "data", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Paid-product promotion is not permitted — share as an open feedback discussion with real substance, at mod discretion.",
        "Coordinated marketing/SEO posts carry a permanent ban with all past posts purged.",
      ],
    }),
  },
  {
    slug: "r-localllama",
    name: "r/LocalLLaMA",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/LocalLLaMA/",
    audienceDesc: "~300k local-LLM enthusiasts",
    rules: "Sharing your own open-source model, tool, or benchmark is welcome when it's genuinely useful, but promotion should stay under ~10% of your activity and closed/paid pitches get pushback. Lead with technical detail and engage.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday evenings ET",
    tags: ["developers", "technical", "ai", "ml", "opensource", "community"],
  },
  {
    slug: "r-cybersecurity",
    name: "r/cybersecurity",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/cybersecurity/",
    audienceDesc: "~900k security professionals",
    rules: "Promotion is formally capped: under 10% of your posts+comments in the sub and at most once a week per product, with automated enforcement. Educational blog posts carrying ads need the 'Corporate Blog' flair; AI-generated content is forbidden sub-wide and soliciting DMs can mean a ban.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "security", "infra", "community"],
    accountRequirements: R_CYBERSECURITY_READINESS,
  },
  {
    slug: "r-netsec",
    name: "r/netsec",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/netsec/",
    audienceDesc: "~600k security researchers",
    rules: "Strictly technical: only original, in-depth security research is allowed and blogspam or product marketing is removed. Company posts must use the flair rules and offer real technical content, not a pitch.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "security", "infra", "writeup", "community"],
  },
  {
    slug: "r-homelab",
    name: "r/homelab",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/homelab/",
    audienceDesc: "~750k self-hosting & homelab enthusiasts",
    rules: "Self-promotion and vendor content are restricted and largely confined to weekly threads; blatant product posts are removed. Share build logs and genuinely useful tools, and disclose if it's yours.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly sticky thread",
    tags: ["developers", "infra", "selfhosted", "devops", "cloud", "community"],
  },
  {
    slug: "r-kubernetes",
    name: "r/kubernetes",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/kubernetes/",
    audienceDesc: "~200k Kubernetes practitioners",
    rules: "Sharing your own open-source K8s tool or write-up is tolerated when it's useful and relevant, but repeated product marketing is removed. Post as a self-post with real technical detail and disclose affiliation.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "infra", "devops", "cloud", "community"],
  },
  {
    slug: "r-sideproject",
    name: "r/SideProject",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/SideProject/",
    audienceDesc: "~250k indie makers & founders",
    rules: "This sub explicitly welcomes sharing your own side projects and launches; just post a genuine build/story, not pure ad copy, and engage with commenters. Avoid low-effort spam and duplicate reposts.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekday mornings ET",
    tags: ["founders", "indie", "makers", "startup", "launch", "showcase"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Use the submit-page title format: '[Project name] - [short description]'.",
      ],
    }),
  },

  // ── Vertical pack: SaaS / indie ──────────────────────────────────
  {
    slug: "r-indiebiz",
    name: "r/indiebiz",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/indiebiz/",
    audienceDesc: "~39k independent & small-business founders",
    rules: "Sharing your services and products is on-topic: post a self-post describing your business and tag the title with the sub's format — [INTRO], [OFFER], [NETWORKING], [RESOURCE], or [REQUEST]. Moderators 'reserve the right to curb spamminess', absolutely no MLM is allowed, and general reddiquette applies.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["founders", "indie", "startup", "makers", "growth"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Tag your title with the sub's format: [INTRO] / [OFFER] / [NETWORKING] / [RESOURCE] / [REQUEST].",
        "No MLM posts of any kind — an explicit sidebar rule.",
      ],
    }),
  },
  {
    slug: "r-entrepreneurridealong",
    name: "r/EntrepreneurRideAlong",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/EntrepreneurRideAlong/",
    audienceDesc: "~710k founders following build-in-public journeys",
    rules: "A large 'build in public' community for following real founder journeys in real time; the only posted rules are be respectful, follow Reddit's global rules, and engage with good intent. There's no formal self-promo ban, but bare launch links read as spam — frame the ship as a transparent progress update (what you built, the numbers, the lesson) and reply to comments.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["founders", "startup", "indie", "growth", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Frame it as a founder-journey update with real numbers and lessons, not a bare launch link.",
      ],
    }),
  },
  {
    slug: "r-microsaas",
    name: "r/microsaas",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/microsaas/",
    audienceDesc: "~200k micro-SaaS founders & indie builders",
    rules: "Sharing your own micro-SaaS is allowed but must add value: 'purely promotional links without context', low-insight build-in-public updates, and repetitive link-dropping are removed. If you post your product you must include the backstory, tech stack, revenue (if comfortable), or a specific lesson learned; no black-hat tactics and no 'DM me' requests.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["saas", "indie", "founders", "product", "startup"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Rule 2: include backstory, tech stack, revenue (if comfortable), or a specific lesson — bare promo is removed.",
      ],
    }),
  },

  // ── Vertical pack: devtools / CLI ────────────────────────────────
  {
    slug: "r-commandline",
    name: "r/commandline",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/commandline/",
    audienceDesc: "~128k CLI/TUI builders & terminal power-users",
    rules: "CLI/TUI projects only (no GUI-only tools), and you must agree to the rules once before your first post and choose a flair. Self-promotion is allowed but gated — projects newer than ~30 days or with only a few commits are removed, you must disclose any affiliation and list similar tools and how yours differs, and AI-generated post text is prohibited (partially AI-generated code must be disclosed).",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "cli", "devtools", "opensource"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Projects newer than ~30 days (or with very few commits) are removed — don't post a day-one launch.",
        "You must agree to the sub's rules once before your first post; disclose affiliation and compare to alternatives.",
        "AI-generated post text/titles are prohibited; disclose any AI-generated code.",
      ],
    }),
  },
  {
    slug: "r-opensource",
    name: "r/opensource",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/opensource/",
    audienceDesc: "~367k open-source developers & maintainers",
    rules: "Self-promotion is permitted 'to a degree' (Reddit's ~10% guideline) as long as you're not a link farm, and sharing your own project REQUIRES the 'Promotional' flair. Hard gate: any linked repo must carry an OSI-approved open-source LICENSE file. AI-generated content is treated as low-effort and 'ban worthy', and titles must match the source (no sensationalizing).",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["opensource", "developers", "software", "showcase", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Use the 'Promotional' flair when sharing your own project.",
        "Your repo must include an OSI-approved open-source LICENSE file or it's off-topic.",
        "No AI-generated content — the sub treats it as ban-worthy.",
      ],
    }),
  },

  // ── Vertical pack: AI tools ──────────────────────────────────────
  {
    slug: "r-artificial",
    name: "r/artificial",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/artificial/",
    audienceDesc: "~1.3M general-AI news & discussion audience",
    rules: "A large general-AI news/discussion sub, not a launch board: Rule 4 bans selling your own products, your first post or comment can't be promotional (the ~10% rule), and 'what's the best tool for X?' posts are removed. Share a genuine AI writeup or research angle and participate first — mods suggest modmailing before posting, and heavy AutoMod filtering targets promo from low-history accounts.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["ai", "ml", "developers", "technical", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Your first post/comment can't be promotional (10% rule); Rule 4 bans selling your own product — share a writeup, not a launch.",
      ],
    }),
  },
  {
    slug: "r-chatgptcoding",
    name: "r/ChatGPTCoding",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/ChatGPTCoding/",
    audienceDesc: "~389k developers using AI to write code",
    rules: "A restricted sub (posting is approval/AutoMod-gated) where every post needs a flair or it's removed. 'Sharing your work' is tolerated in the main feed, but overt service/product promotion belongs in the designated self-promo thread or requires applying for a sponsorship via modmail; include the prompt you used when you post generated code, and don't sell model access.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["ai", "developers", "technical", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "The sub is 'restricted' — posting is approval-gated, and every post must carry a flair.",
        "Overt product/service promotion goes in the self-promo thread or via a modmail sponsorship — 'sharing your work' is tolerated in the main feed.",
      ],
    }),
  },
  {
    slug: "r-aipromptprogramming",
    name: "r/aipromptprogramming",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/aipromptprogramming/",
    audienceDesc: "~233k AI-tools & prompt-engineering builders",
    rules: "A restricted 'AI hackerspace' feed for AI tools in programming and prompt engineering. Posts must stay on-topic and English-only; the written Rule 6 prohibits self-promotion and ads for commercial products, so keep posts genuinely educational (how the tool helps) rather than a launch pitch — posting is approval/AutoMod-gated.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["ai", "developers", "technical", "makers"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Rule 6 officially prohibits self-promotion/ads — post genuinely educational content, not a launch pitch.",
        "The sub is 'restricted' (posting is approval-gated).",
      ],
    }),
  },

  // ── Vertical pack: Mac / desktop ─────────────────────────────────
  {
    slug: "r-macapps",
    name: "r/macapps",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/macapps/",
    audienceDesc: "~238k Mac app enthusiasts · the most promo-friendly Mac sub",
    rules: "Self-promotion is explicitly allowed but tightly gated. You need 10 karma earned inside r/MacApps and post approval before posting, the correct flair (Lifetime > Subscription > Free; [OS] for open source), and official links only (Mac App Store or your own site — no third-party hosts, redirect/shortened, or affiliate links). Promotion is capped at once per developer per 30 days; devs who don't qualify for the main feed must use the monthly megathread.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["macos", "desktop", "product", "software", "showcase"],
    accountRequirements: MACAPPS_READINESS,
  },
  {
    slug: "r-macos",
    name: "r/macOS",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/macos/",
    audienceDesc: "~603k general macOS discussion & support community",
    rules: "A general macOS discussion/support community, not a showcase: self-promotion is permitted ONLY on Saturdays (UTC) and only for apps on the Mac App Store or reputable, established GitHub repos (all GitHub links are auto-audited by 'GitHub Guard', and off-whitelist domains are auto-removed). Promotional posts any other day are removed; 'curl | sh' pipe-to-shell commands are auto-removed.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Saturdays (UTC)",
    tags: ["macos", "desktop", "community", "apple", "software"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Self-promotion is allowed ONLY on Saturdays (UTC), and only for Mac App Store apps or established GitHub repos.",
        "New/low-reputation GitHub repos may be filtered by 'GitHub Guard'; off-whitelist domains are auto-removed.",
      ],
    }),
  },
  {
    slug: "r-apple",
    name: "r/apple",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/apple/",
    audienceDesc: "~6.4M unofficial Apple community · general, strictly moderated",
    rules: "A huge, strictly moderated general Apple community. Developer self-promotion is allowed only on Sundays (California time) and only as a self-post, and activity requirements are enforced — you're expected to have participated organically (unrelated posts/comments) rather than showing up only to promote. No YouTube/tweet self-promo, and no tech-support or 'what should I buy' posts.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Sundays (California time)",
    tags: ["apple", "macos", "mobile", "community", "product"],
    accountRequirements: redditReadiness({
      minAccountAgeDays: 30,
      extraTips: [
        "Developer self-promo is Sundays-only (California time), self-post only.",
        "Activity requirements are enforced — build genuine, unrelated participation in r/apple before you promote.",
      ],
    }),
  },

  // ── Vertical pack: privacy / security ────────────────────────────
  {
    slug: "r-privacy",
    name: "r/privacy",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/privacy/",
    audienceDesc: "~1.6M digital-privacy discussion community",
    rules: "A strict privacy discussion sub that effectively bans promotion: Rule 3 forbids advertising or marketing products, services, websites, or social accounts (including affiliate/referral links and content-creator promotion); Rule 13 has put app-promotion requests 'on hold' — even open-source; and Rule 7 bans promoting closed-source software. Don't launch here — contribute to the discussion instead (surveys/fundraising also need prior approval).",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Not a promo venue — contribute only",
    tags: ["privacy", "security", "community", "technical", "developers"],
  },
  {
    slug: "r-opsec",
    name: "r/opsec",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/opsec/",
    audienceDesc: "~76k operational-security methodology community",
    rules: "An operational-security methodology sub built around threat modeling, not product posts. You must read the pinned rules thread and state your threat model before posting, and 'don't just name a tool' — single-tool/product recommendations without a threat-model rationale are removed. There's no self-promotion lane, so a launch post is off-culture here.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Not a promo venue — contribute only",
    tags: ["privacy", "security", "technical", "community"],
  },

  // ── Vertical pack: hardware / EE ─────────────────────────────────
  {
    slug: "r-printedcircuitboard",
    name: "r/PrintedCircuitBoard",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/PrintedCircuitBoard/",
    audienceDesc: "~98k PCB designers doing schematic/layout reviews",
    rules: "The official PCB design-review sub, scoped to schematic/layout review requests only. Rule 2 bans spam/ads/sales/promotion/surveys, Rule 3 bans 'show & tell / look what I made' posts unless you previously ran a review of the same board, Rule 4 bans self-promotion/job-seeking, and Rule 5 bans shilling (no PCB company names in titles). Don't launch here — post a genuine design review or contribute.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Not a promo venue — reviews only",
    tags: ["hardware", "electronics", "pcb", "makers", "technical"],
  },
  {
    slug: "r-askelectronics",
    name: "r/AskElectronics",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/AskElectronics/",
    audienceDesc: "~930k component-level electronics Q&A community",
    rules: "A component-level electronics Q&A help sub. Rule 4 flatly prohibits advertisements, commercial offers, giveaways, spam, and self-promotion, and trading is not allowed. Posts must be clear, on-topic questions (descriptive title, basic diagnostics) — it's not a venue to launch a product, so engage by genuinely answering questions instead.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Not a promo venue — Q&A only",
    tags: ["electronics", "hardware", "technical", "community"],
  },
  {
    slug: "r-embedded",
    name: "r/embedded",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/embedded/",
    audienceDesc: "~274k embedded-systems engineers & hobbyists",
    rules: "An embedded-systems discussion/Q&A sub. Rule 4 bars spam, commercial posts, links to commercial/crowdfunding pages, and self-promotion — but at moderator discretion, self-promo from people who genuinely contribute in other ways may be allowed and tagged with the 'Self-promo' flair. Keep posts on-topic (a micro is involved), put the actual question in the title, and earn goodwill by helping before you share.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["embedded", "firmware", "hardware", "developers", "technical"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Rule 4 bans self-promo by default; a mod-discretion 'Self-promo' flair lane exists for people who contribute to the sub in other ways.",
        "Contribute genuine help first, then share tagged as 'Self-promo'.",
      ],
    }),
  },
];
