import { Platform, BanRisk } from "@prisma/client";
import type { Seed } from "./types";
import { redditReadiness, R_CYBERSECURITY_READINESS } from "./requirements";

/** Niche language/framework/domain subreddits (verified real, promo rules honest). */
export const subreddits: Seed[] = [
  {
    slug: "r-rust",
    name: "r/rust",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/rust/",
    audienceDesc: "~300k Rust developers",
    rules: "Show-and-tell of your own Rust projects is welcome as a self-post, but blatant marketing and low-effort link drops get removed. Lead with the technical story (what you built, how, what's interesting) rather than a sales pitch, and be present to answer questions.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "opensource", "backend", "community", "rust"],
    accountRequirements: redditReadiness(),
  },
  {
    slug: "r-golang",
    name: "r/golang",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/golang/",
    audienceDesc: "~250k Go developers",
    rules: "Sharing your own Go library or tool is allowed if it's genuinely useful and posted as a self-post with context, but pure promotion and paid products get flagged. Explain the problem it solves and engage in the comments.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "opensource", "community", "golang"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Small/new projects (months of effort, one contributor) belong in the weekly 'Small Projects' thread per the project-requirements wiki.",
        "No emoji, engagement hooks, or AI-generated text in project posts — a couple of plain paragraphs on purpose and results.",
      ],
    }),
  },
  {
    slug: "r-python",
    name: "r/Python",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/Python/",
    audienceDesc: "~1.3M Python developers",
    rules: "Project posts must follow the 'Showcase' format with a required 'What My Project Does / Target Audience / Comparison' write-up; low-effort or purely promotional links are removed. There's a weekly thread for smaller shares.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "opensource", "backend", "community", "python"],
    accountRequirements: redditReadiness({
      extraTips: ["Use the required Showcase format (What My Project Does / Target Audience / Comparison)."],
    }),
  },
  {
    slug: "r-django",
    name: "r/django",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/django/",
    audienceDesc: "~130k Django developers",
    rules: "Sharing your own Django project, package, or tutorial is tolerated when it adds value and is clearly relevant, but repeated promotion of a paid product is not. Post as a self-post with technical detail and answer questions.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "python", "django"],
    accountRequirements: redditReadiness({
      extraTips: [
        "The sub's own rules warn: share your work, but participate in other ways too 'or the spam algorithm might get you'.",
      ],
    }),
  },
  {
    slug: "r-reactjs",
    name: "r/reactjs",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/reactjs/",
    audienceDesc: "~400k React developers",
    rules: "Self-promotion and 'I built X' posts are funneled into the pinned weekly 'Show /r/reactjs' thread; standalone promo posts are removed. Share there with a real description and be ready to discuss the code.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly Show thread",
    tags: ["developers", "frontend", "webdev", "javascript", "react", "community"],
    accountRequirements: redditReadiness({
      minAccountAgeDays: 60,
      minKarma: 250,
      extraTips: ["'I built X' posts go in the pinned weekly Show thread; standalone promo is removed."],
    }),
  },
  {
    slug: "r-vuejs",
    name: "r/vuejs",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/vuejs/",
    audienceDesc: "~100k Vue developers",
    rules: "Sharing your own Vue library, tool, or article is allowed if it's on-topic and useful, but low-effort self-promo and spam are removed. Post as a self-post, explain what it does, and engage with feedback.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "frontend", "webdev", "javascript", "vue", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "The sub's rule allows self-promo 'in a tasteful way' — don't flood the feed with your own links.",
      ],
    }),
  },
  {
    slug: "r-sveltejs",
    name: "r/sveltejs",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/sveltejs/",
    audienceDesc: "~55k Svelte developers",
    rules: "Show-and-tell of your own Svelte projects and libraries is welcome when clearly relevant, but pure marketing gets removed. Lead with what you built and why, and take part in the discussion.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "frontend", "webdev", "javascript", "svelte", "community"],
  },
  {
    slug: "r-rails",
    name: "r/rails",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/rails/",
    audienceDesc: "~80k Ruby on Rails developers",
    rules: "Sharing your own gem, tool, or Rails write-up is accepted when it's genuinely useful to Rails devs, but repetitive product promotion is not. Post as a self-post with technical context and answer questions.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "ruby", "rails"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Label AI-assisted content clearly — the sub added a 'no AI slop' rule.",
        "Hiring/job posts go in the biweekly 'Work it Wednesday' thread, not the feed.",
      ],
    }),
  },
  {
    slug: "r-laravel",
    name: "r/laravel",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/laravel/",
    audienceDesc: "~90k Laravel developers",
    rules: "Self-promotion of your own packages or products is limited and must follow the subreddit's promo guidelines (often a designated thread); undisclosed or repeated promo is removed. Disclose that it's yours and provide real value.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "php", "laravel"],
  },
  {
    slug: "r-php",
    name: "r/PHP",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/PHP/",
    audienceDesc: "~170k PHP developers",
    rules: "This is a discussion-focused sub: self-promotion, product launches, and 'check out my thing' posts are heavily restricted and often removed. Share only substantive technical content and disclose any affiliation.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "webdev", "php", "community"],
  },
  {
    slug: "r-dotnet",
    name: "r/dotnet",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/dotnet/",
    audienceDesc: "~230k .NET developers",
    rules: "Sharing your own open-source library or article is allowed when relevant and useful, but blatant product promotion and spam are removed. Post as a self-post, explain the technical value, and engage.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "dotnet", "csharp", "community"],
  },
  {
    slug: "r-csharp",
    name: "r/csharp",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/csharp/",
    audienceDesc: "~300k C# developers",
    rules: "Self-promotion is restricted and must follow the 90/10 rule; standalone promo and paid-product posts are frequently removed. Share open-source, technically substantive content and disclose that it's yours.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "dotnet", "csharp", "community"],
  },
  {
    slug: "r-java",
    name: "r/java",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/java/",
    audienceDesc: "~450k Java developers",
    rules: "This is a strictly moderated news/discussion sub for experienced Java devs; self-promotion, beginner content, and 'I made X' posts are largely disallowed. Only share high-quality, on-topic technical articles or projects.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "backend", "java", "community"],
  },
  {
    slug: "r-androiddev",
    name: "r/androiddev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/androiddev/",
    audienceDesc: "~200k Android developers",
    rules: "App promotion and self-promo are restricted to the weekly threads; standalone 'check out my app' posts are removed. Share libraries or technical write-ups directly, but push app launches into the designated thread.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly promo thread",
    tags: ["developers", "technical", "mobile", "android", "kotlin", "community"],
  },
  {
    slug: "r-iosprogramming",
    name: "r/iOSProgramming",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/iOSProgramming/",
    audienceDesc: "~110k iOS developers",
    rules: "App and self-promotion are funneled into the weekly 'Self Promotion Saturday' thread; promo posts outside it are removed. Share your app or product there and contribute technical value the rest of the week.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Self Promotion Saturday",
    tags: ["developers", "technical", "mobile", "ios", "swift", "community"],
  },
  {
    slug: "r-swift",
    name: "r/swift",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/swift/",
    audienceDesc: "~90k Swift developers",
    rules: "Sharing your own Swift library, tool, or article is allowed when relevant, but app-store marketing and repeated promo are removed. Post as a self-post focused on the code and engage with feedback.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "mobile", "ios", "swift", "community"],
  },
  {
    slug: "r-flutterdev",
    name: "r/FlutterDev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/FlutterDev/",
    audienceDesc: "~180k Flutter developers",
    rules: "Self-promotion is allowed but capped by the 90/10 rule and must be flaired as promotion; spammy or undisclosed promo is removed. Share packages and apps with real context and take part in the community.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "mobile", "flutter", "opensource", "community"],
  },
  {
    slug: "r-gamedev",
    name: "r/gamedev",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/gamedev/",
    audienceDesc: "~1.3M game developers",
    rules: "This sub is for development discussion, not marketing: showcasing your game at any stage is banned, and posts that are only a link to a game or social page are a documented ban. Share postmortems, process, and marketing lessons here — launch the game itself on r/indiegames or r/playmygame.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Anytime (discussion only)",
    tags: ["developers", "technical", "gamedev", "makers", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Don't launch the game here — showcasing is banned at any dev stage; write a postmortem or feedback request instead.",
        "Link-only posts to game/social pages 'will result in a ban' per the sub's rules.",
      ],
    }),
  },
  {
    slug: "r-datascience",
    name: "r/datascience",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/datascience/",
    audienceDesc: "~1.5M data scientists",
    rules: "Self-promotion, tool launches, and blog links are tightly moderated and mostly funneled into weekly threads; standalone promo is removed. Share only genuinely useful, non-salesy content and disclose affiliation.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly sticky thread",
    tags: ["developers", "technical", "data", "ml", "python", "community"],
  },
  {
    slug: "r-machinelearning",
    name: "r/MachineLearning",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/MachineLearning/",
    audienceDesc: "~3M ML researchers & engineers",
    rules: "A research-focused sub: promotion of paid products is not permitted, and a project link passes only when the post offers real substance and invites discussion. Coordinated marketing or SEO posts mean a permanent ban with your history purged; bare paper links without commentary are removed.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "ml", "ai", "data", "community"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Paid-product promotion is not permitted — share as an open feedback discussion with real substance, at mod discretion.",
        "Coordinated marketing/SEO posts carry a permanent ban with all past posts purged.",
      ],
    }),
  },
  {
    slug: "r-localllama",
    name: "r/LocalLLaMA",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/LocalLLaMA/",
    audienceDesc: "~300k local-LLM enthusiasts",
    rules: "Sharing your own open-source model, tool, or benchmark is welcome when it's genuinely useful, but promotion should stay under ~10% of your activity and closed/paid pitches get pushback. Lead with technical detail and engage.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday evenings ET",
    tags: ["developers", "technical", "ai", "ml", "opensource", "community"],
  },
  {
    slug: "r-cybersecurity",
    name: "r/cybersecurity",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/cybersecurity/",
    audienceDesc: "~900k security professionals",
    rules: "Promotion is formally capped: under 10% of your posts+comments in the sub and at most once a week per product, with automated enforcement. Educational blog posts carrying ads need the 'Corporate Blog' flair; AI-generated content is forbidden sub-wide and soliciting DMs can mean a ban.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "security", "infra", "community"],
    accountRequirements: R_CYBERSECURITY_READINESS,
  },
  {
    slug: "r-netsec",
    name: "r/netsec",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/netsec/",
    audienceDesc: "~600k security researchers",
    rules: "Strictly technical: only original, in-depth security research is allowed and blogspam or product marketing is removed. Company posts must use the flair rules and offer real technical content, not a pitch.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "security", "infra", "writeup", "community"],
  },
  {
    slug: "r-homelab",
    name: "r/homelab",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/homelab/",
    audienceDesc: "~750k self-hosting & homelab enthusiasts",
    rules: "Self-promotion and vendor content are restricted and largely confined to weekly threads; blatant product posts are removed. Share build logs and genuinely useful tools, and disclose if it's yours.",
    defaultBanRisk: BanRisk.HIGH,
    bestTime: "Weekly sticky thread",
    tags: ["developers", "infra", "selfhosted", "devops", "cloud", "community"],
  },
  {
    slug: "r-kubernetes",
    name: "r/kubernetes",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/kubernetes/",
    audienceDesc: "~200k Kubernetes practitioners",
    rules: "Sharing your own open-source K8s tool or write-up is tolerated when it's useful and relevant, but repeated product marketing is removed. Post as a self-post with real technical detail and disclose affiliation.",
    defaultBanRisk: BanRisk.MEDIUM,
    bestTime: "Weekday mornings ET",
    tags: ["developers", "technical", "infra", "devops", "cloud", "community"],
  },
  {
    slug: "r-sideproject",
    name: "r/SideProject",
    platform: Platform.REDDIT,
    url: "https://www.reddit.com/r/SideProject/",
    audienceDesc: "~250k indie makers & founders",
    rules: "This sub explicitly welcomes sharing your own side projects and launches; just post a genuine build/story, not pure ad copy, and engage with commenters. Avoid low-effort spam and duplicate reposts.",
    defaultBanRisk: BanRisk.LOW,
    bestTime: "Weekday mornings ET",
    tags: ["founders", "indie", "makers", "startup", "launch", "showcase"],
    accountRequirements: redditReadiness({
      extraTips: [
        "Use the submit-page title format: '[Project name] - [short description]'.",
      ],
    }),
  },
];
